### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by marnen** [Gianfrancoalongi/APLUnit#27]
It is not clear how this library is licensed. I'd like to use it in an open-source project of mine, but I can't be comfortable doing so until it has an explicit license. 

So...please add a license file of your choice.

**Comment by Gianfrancoalongi** [comment]
Good point!

**Comment by Gianfrancoalongi** [comment]
Done https://github.com/Gianfrancoalongi/APLUnit/commit/305d9a47b780118513bd85b3b5a34f6dd179033f

**Comment by marnen** [comment]
Thanks so much!

**Comment by marnen** [comment]
BTW, as a matter of style, most people put the license in a file called LICENSE or something, in order not to clutter the README with it. I'll make a pull request for that if you want.

**Comment by Gianfrancoalongi** [comment]
Sure go ahead. :)
